# Generated by Django 4.2.13 on 2026-04-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_url",
            field=models.URLField(unique=True),
        ),
    ]
